    - name: Download Node.js tarball
      get_url:
        url: "https://nodejs.org/dist/latest/node-{{ node_version }}-linux-x64.tar.xz"
        dest: "/tmp/node-{{ node_version }}-linux-x64.tar.xz"
        mode: '0644'

    - name: Extract Node.js tarball
      unarchive:
        src: "/tmp/node-{{ node_version }}-linux-x64.tar.xz"
        dest: "/usr/local/"
        remote_src: yes

    - name: Create symlinks for node and npm
      file:
        src: "/usr/local/node-{{ node_version }}-linux-x64/bin/{{ item }}"
        dest: "/usr/bin/{{ item }}"
        state: link
        force: yes
      loop:
        - node
        - npm
        - npx

    - name: delete nodejs tarball
      file: 
        path: "/tmp/node-{{ node_version }}-linux-x64.tar.xz"
        state: absent

    - name: Verify Node.js installation
      command: node -v && npm -v && npx -v
      register: node_version